name: E2E Tests

on: [push, pull_request]

jobs:
  cypress-run:
    name: e2e testing with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run dev
          start: npm run server:test
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          record: true
          browser: true
      - name: Build web app
        run: npm run build
